### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Clnzie** [SattyaP/rest-api-mongoexpress#1]
API error:

- Get by slug
- Put
- Delete

**Comment by SattyaP** [comment]
> API error:
> 
> - Get by slug
> - Put
> - Delete

In Proggress 👍

**Comment by SattyaP** [comment]
> API error:
> 
> * Get by slug
> * Put
> * Delete

Hi. 
Good Day for you the bug is already fixed please read full information on the docs page 
Alternative links here : [https://rest-api-mongoexpress.vercel.app/docs](https://rest-api-mongoexpress.vercel.app/docs)

**Comment by SattyaP** [comment]
> > API error:
> > 
> > * Get by slug
> > * Put
> > * Delete
> 
> Hi. Good Day for you the bug is already fixed please read full information on the docs page Alternative links here : [https://rest-api-mongoexpress.vercel.app/docs](url)

Pay attention to the endpoints as they have undergone changes @Clnzie
